# Generated by Django 3.2.6 on 2021-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiring', models.BooleanField(default=False)),
                ('wiring_detail', models.TextField(max_length=200)),
                ('assembly', models.BooleanField(default=False)),
                ('assembly_detail', models.TextField(max_length=200)),
                ('assembly_qa', models.BooleanField(default=False)),
                ('assembly_qa_detail', models.TextField(max_length=200)),
                ('technosoft', models.BooleanField(default=False)),
                ('technosoft_detail', models.TextField(max_length=200)),
                ('captrack', models.BooleanField(default=False)),
                ('captrack_detail', models.TextField(max_length=200)),
                ('final_qa', models.BooleanField(default=False)),
                ('final_qa_detail', models.TextField(max_length=200)),
            ],
        ),
    ]
