# Generated by Django 3.2.6 on 2021-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='assembly_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pt',
            name='assembly_qa_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pt',
            name='captrack_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pt',
            name='final_qa_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pt',
            name='technosoft_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pt',
            name='wiring_detail',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
