# Generated by Django 3.2.6 on 2021-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0002_auto_20210826_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt',
            name='client',
            field=models.CharField(default='Capture', max_length=20),
        ),
    ]
